apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solarease-prod

resources:
  - ../../base

commonLabels:
  environment: prod

patches:
  - target:
      kind: Deployment
      name: gateway-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: identity-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: project-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: dimensioning-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: ConfigMap
      name: solarease-config
    patch: |-
      - op: replace
        path: /data/SOLAREASE_DEMO_SEED
        value: "false"
      - op: replace
        path: /data/SPRING_JPA_HIBERNATE_DDL_AUTO
        value: "validate"
