@startuml uc-client-modifier-profil
title Diagramme de cas d'utilisation -- Client modifie son profil (Sprint 1)

left to right direction
skinparam shadowing false
skinparam usecase {
    BackgroundColor #FFFFFF
    BorderColor     #2C5282
}
skinparam actor {
    BorderColor #2C5282
}

actor Client

rectangle "Identity Service" {
    usecase "S'authentifier"              as UC_Auth
    usecase "Consulter son profil"        as UC_View
    usecase "Modifier ses\ninformations"  as UC_Update
    usecase "Changer son\nmot de passe"   as UC_ChangePwd
}

Client --> UC_Auth
Client --> UC_View
Client --> UC_Update
Client --> UC_ChangePwd

UC_View       ..> UC_Auth : <<include>>
UC_Update     ..> UC_Auth : <<include>>
UC_ChangePwd  ..> UC_Auth : <<include>>

@enduml
