package com.solarease.service;

import com.solarease.dto.DimensioningResponse;
import com.solarease.dto.FinancialMetrics;
import com.solarease.entity.Equipment;
import com.solarease.entity.SolarInstallation;
import com.solarease.rag.CompatibilityRuleEngine;
import com.solarease.rag.EmbeddingService;
import com.solarease.rag.EquipmentSelectionService;
import com.solarease.rag.InstallerRecommendationDto;
import com.solarease.rag.KnowledgeChunk;
import com.solarease.rag.KnowledgeChunkRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Hybrid RAG pipeline that combines deterministic rules and semantic
 * retrieval over the {@code knowledge_chunks} pgvector table.
 *
 * <p>The pipeline runs in three stages:</p>
 * <ol>
 *   <li><b>Deterministic kit</b> -- {@link EquipmentSelectionService} and
 *       {@link CompatibilityRuleEngine} produce the inverter, cables and
 *       Schneider breakers from the company catalog plus a score and
 *       structured alerts. This part never depends on the LLM and is
 *       therefore reproducible.</li>
 *   <li><b>Vector retrieval</b> -- a query embedding is generated by
 *       {@link EmbeddingService} and matched against {@code knowledge_chunks}
 *       to surface the most relevant equipment, sizing rules and
 *       regulations.</li>
 *   <li><b>Narrative augmentation</b> -- the kit, the chunks and the project
 *       numbers are sent to Ollama to enrich the recommendation with
 *       installer-friendly bullet points (alerts, sales arguments, terrain
 *       checklist, narrative summary).</li>
 * </ol>
 *
 * <p>If either Ollama call (embedding or generation) fails, the deterministic
 * kit and verdict are still returned and the {@code fallback} flag is set.</p>
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class DecisionSupportService {

    private static final int RETRIEVAL_TOPK = 5;

    private final OllamaService ollamaService;
    private final EmbeddingService embeddingService;
    private final KnowledgeChunkRepository chunkRepository;
    private final EquipmentSelectionService selectionService;
    private final CompatibilityRuleEngine ruleEngine;

    /**
     * Public entry point used by the dimensioning flow. Builds the structured
     * recommendation and returns it together with a textual summary that is
     * compatible with the previous {@code aiRecommendation} field of
     * {@code DimensioningResponse}.
     */
    public Result generate(DimensioningResponse dimensioning,
                           Equipment usedPanel,
                           Equipment usedInverter) {
        return generate(dimensioning, usedPanel, usedInverter, true);
    }

    /**
     * Fast path for {@code /calculate}: deterministic kit + narrative only.
     * Skips Ollama embedding/LLM so the HTTP response stays under Vercel's proxy limit.
     */
    public Result generateDeterministic(DimensioningResponse dimensioning,
                                        Equipment usedPanel,
                                        Equipment usedInverter) {
        return generate(dimensioning, usedPanel, usedInverter, false);
    }

    private Result generate(DimensioningResponse dimensioning,
                            Equipment usedPanel,
                            Equipment usedInverter,
                            boolean withLlmAugmentation) {
        SolarInstallation installation = dimensioning.getInstallation();
        if (installation == null || installation.getTotalCapacityKw() == null) {
            InstallerRecommendationDto empty = InstallerRecommendationDto.builder()
                    .verdict("NON_COMPATIBLE")
                    .compatibilityScore(0)
                    .fallback(true)
                    .narrativeSummary("Aucune installation calculée.")
                    .build();
            return new Result(empty, empty.getNarrativeSummary());
        }

        double requiredKw = installation.getTotalCapacityKw();
        SelectedKit selected = assembleKit(requiredKw, usedInverter);
        CompatibilityRuleEngine.Result evaluation = ruleEngine.evaluate(
                requiredKw, selected.inverter(),
                selected.kit().getDcCable(), selected.dcBreaker(), selected.acBreaker());

        InstallerRecommendationDto dto = InstallerRecommendationDto.builder()
                .verdict(evaluation.verdict())
                .compatibilityScore(evaluation.score())
                .recommendedKit(selected.kit())
                .alternatives(buildAlternatives(selected.inverter(), requiredKw))
                .alerts(new ArrayList<>(evaluation.alerts()))
                .clientArguments(new ArrayList<>())
                .terrainChecklist(new ArrayList<>())
                .ragSources(new ArrayList<>())
                .build();

        if (withLlmAugmentation) {
            try {
                List<KnowledgeChunk> chunks = retrieveChunks(installation, selected.kit());
                dto.getRagSources().addAll(toSourceLabels(chunks));

                String prompt = buildPrompt(installation, dimensioning.getFinancials(),
                        selected.kit(), dto, chunks);
                String llmAnswer = ollamaService.generate(prompt);
                applyLlmAnswer(dto, llmAnswer);
            } catch (Exception e) {
                log.warn("RAG augmentation skipped, returning deterministic kit only: {}",
                        e.getMessage());
                dto.setFallback(true);
                applyDeterministicNarrative(dto, installation, dimensioning.getFinancials());
            }
        } else {
            dto.setFallback(true);
            applyDeterministicNarrative(dto, installation, dimensioning.getFinancials());
        }

        if (dto.getNarrativeSummary() == null || dto.getNarrativeSummary().isBlank()) {
            applyDeterministicNarrative(dto, installation, dimensioning.getFinancials());
        }

        return new Result(dto, dto.getNarrativeSummary());
    }

    /**
     * Backwards-compatible wrapper. The PDF generator and the existing flow
     * still call this method, expecting a single string. We keep the same
     * signature but route through the new pipeline.
     */
    public String generateAiRecommendation(DimensioningResponse dimensioning,
                                           Equipment usedPanel,
                                           Equipment usedInverter) {
        return generate(dimensioning, usedPanel, usedInverter).narrativeSummary();
    }

    // ───────────────────────────────────────────────────────────────────
    // Deterministic kit assembly
    // ───────────────────────────────────────────────────────────────────

    /** Kit DTO plus the catalog {@link Equipment} rows used for scoring. */
    private record SelectedKit(InstallerRecommendationDto.RecommendedKit kit,
                               Equipment inverter,
                               Equipment dcBreaker,
                               Equipment acBreaker) {}

    private SelectedKit assembleKit(double requiredKw, Equipment fallbackInverter) {
        Equipment inverter = selectionService.selectInverter(requiredKw)
                .orElse(fallbackInverter);
        String phase = readPhase(inverter);

        Equipment dcBreaker = selectionService.selectDcBreaker(requiredKw).orElse(null);
        Equipment acBreaker = selectionService.selectAcBreaker(requiredKw, phase).orElse(null);

        InstallerRecommendationDto.KitInverter inverterDto = inverter == null
                ? null
                : InstallerRecommendationDto.KitInverter.builder()
                        .equipmentId(inverter.getId())
                        .brand(inverter.getBrand())
                        .model(inverter.getModel())
                        .powerKw(inverter.getNominalPower() == null
                                ? 0.0 : inverter.getNominalPower() / 1000.0)
                        .phase(phase)
                        .price(inverter.getPrice())
                        .build();

        InstallerRecommendationDto.RecommendedKit kit =
                InstallerRecommendationDto.RecommendedKit.builder()
                .inverter(inverterDto)
                .dcCable(selectionService.selectDcCable(requiredKw))
                .acCable(selectionService.selectAcCable(requiredKw))
                .dcBreaker(toBreakerDto(dcBreaker, "DC string protection"))
                .acBreaker(toBreakerDto(acBreaker, "AC inverter output"))
                .totalKitPrice(selectionService.totalKitPrice(
                        inverter, dcBreaker, acBreaker))
                .build();

        return new SelectedKit(kit, inverter, dcBreaker, acBreaker);
    }

    private InstallerRecommendationDto.KitBreaker toBreakerDto(Equipment e, String app) {
        if (e == null) return null;
        Integer rating = readInt(e.getSpecifications(), "ratingA");
        String ref = readString(e.getSpecifications(), "schneiderRef");
        return InstallerRecommendationDto.KitBreaker.builder()
                .equipmentId(e.getId())
                .brand(e.getBrand())
                .reference(ref != null ? ref : e.getModel())
                .ratingA(rating != null ? rating : 0)
                .application(app)
                .price(e.getPrice())
                .build();
    }

    private List<InstallerRecommendationDto.KitInverter> buildAlternatives(
            Equipment used, double requiredKw) {
        return selectionService.selectAlternatives(used, requiredKw, 2).stream()
                .map(e -> InstallerRecommendationDto.KitInverter.builder()
                        .equipmentId(e.getId())
                        .brand(e.getBrand())
                        .model(e.getModel())
                        .powerKw(e.getNominalPower() == null
                                ? 0.0 : e.getNominalPower() / 1000.0)
                        .phase(readPhase(e))
                        .price(e.getPrice())
                        .build())
                .collect(Collectors.toList());
    }

    // ───────────────────────────────────────────────────────────────────
    // Vector retrieval
    // ───────────────────────────────────────────────────────────────────

    private List<KnowledgeChunk> retrieveChunks(SolarInstallation installation,
                                                InstallerRecommendationDto.RecommendedKit kit) {
        String query = buildRetrievalQuery(installation, kit);
        float[] vector = embeddingService.embed(query);
        return chunkRepository.search(vector, RETRIEVAL_TOPK, null);
    }

    private String buildRetrievalQuery(SolarInstallation installation,
                                       InstallerRecommendationDto.RecommendedKit kit) {
        StringBuilder q = new StringBuilder("Installation solaire en Tunisie ");
        if (installation.getTotalCapacityKw() != null) {
            q.append(String.format("%.1f kWc ", installation.getTotalCapacityKw()));
        }
        if (kit != null && kit.getInverter() != null && kit.getInverter().getPhase() != null) {
            q.append("MONO".equalsIgnoreCase(kit.getInverter().getPhase())
                    ? "monophasée " : "triphasée ");
        }
        q.append("choix onduleur, section câble DC, disjoncteur Schneider, ")
                .append("réglementation STEG, ANME, conseils terrain.");
        return q.toString();
    }

    private List<String> toSourceLabels(List<KnowledgeChunk> chunks) {
        return chunks.stream()
                .map(c -> "chunk-" + c.getId() + ":" + c.getSourceType())
                .toList();
    }

    // ───────────────────────────────────────────────────────────────────
    // LLM augmentation
    // ───────────────────────────────────────────────────────────────────

    private String buildPrompt(SolarInstallation installation,
                               FinancialMetrics financials,
                               InstallerRecommendationDto.RecommendedKit kit,
                               InstallerRecommendationDto draft,
                               List<KnowledgeChunk> chunks) {
        StringBuilder p = new StringBuilder();
        p.append("Tu es un expert solaire en Tunisie qui assiste un installateur. ")
                .append("Le kit ci-dessous a déjà été choisi par le moteur déterministe ; ")
                .append("ne recalcule pas la puissance, complète seulement les sections demandées.\n\n");

        p.append("DONNÉES PROJET :\n");
        if (installation.getTotalCapacityKw() != null) {
            p.append("- Puissance crête : ")
                    .append(String.format("%.2f kWc%n", installation.getTotalCapacityKw()));
        }
        if (installation.getEstimatedAnnualProductionKwh() != null) {
            p.append("- Production annuelle estimée : ")
                    .append(String.format("%.0f kWh%n",
                            installation.getEstimatedAnnualProductionKwh()));
        }
        if (financials != null) {
            p.append(String.format(
                    "- Investissement : %.0f TND | ROI : %.1f%% | Payback : %.1f ans%n",
                    nz(financials.getTotalInvestmentCost()),
                    nz(financials.getRoiPercentage()),
                    nz(financials.getPaybackPeriodYears())));
        }

        p.append("\nKIT RETENU :\n");
        if (kit.getInverter() != null) {
            p.append("- Onduleur : ").append(kit.getInverter().getBrand()).append(' ')
                    .append(kit.getInverter().getModel()).append(" (")
                    .append(String.format("%.1f kW", kit.getInverter().getPowerKw()))
                    .append(", ").append(kit.getInverter().getPhase()).append(")\n");
        }
        if (kit.getDcCable() != null) {
            p.append("- Câble DC : ").append(kit.getDcCable().getSectionMm2())
                    .append(" mm² (").append(kit.getDcCable().getStandard()).append(")\n");
        }
        if (kit.getAcCable() != null) {
            p.append("- Câble AC : ").append(kit.getAcCable().getSectionMm2())
                    .append(" mm² (").append(kit.getAcCable().getStandard()).append(")\n");
        }
        if (kit.getDcBreaker() != null) {
            p.append("- Disjoncteur DC : ").append(kit.getDcBreaker().getReference())
                    .append(" / ").append(kit.getDcBreaker().getRatingA()).append(" A\n");
        }
        if (kit.getAcBreaker() != null) {
            p.append("- Disjoncteur AC : ").append(kit.getAcBreaker().getReference())
                    .append(" / ").append(kit.getAcBreaker().getRatingA()).append(" A\n");
        }
        p.append("- Score compatibilité : ").append(draft.getCompatibilityScore())
                .append(" / 100 (").append(draft.getVerdict()).append(")\n");

        if (!chunks.isEmpty()) {
            p.append("\nDOCUMENTATION RAG (extraits du catalogue + règles + STEG/ANME) :\n");
            for (KnowledgeChunk c : chunks) {
                p.append("• ").append(c.getContent()).append('\n');
            }
        }

        p.append("\nFOURNIS LA RÉPONSE EXACTEMENT DANS CE FORMAT MARKDOWN :\n");
        p.append("RESUME: <2 phrases techniques sur le kit>\n");
        p.append("ALERTES:\n- <alerte courte>\n- <alerte courte>\n");
        p.append("ARGUMENTS_CLIENT:\n- <argument vente>\n- <argument vente>\n- <argument vente>\n");
        p.append("CHECKLIST_TERRAIN:\n- <étape>\n- <étape>\n- <étape>\n");
        p.append("Pas de bavardage hors sections, maximum 4 lignes par section.");

        return p.toString();
    }

    private void applyLlmAnswer(InstallerRecommendationDto dto, String llmAnswer) {
        if (llmAnswer == null || llmAnswer.isBlank()) {
            dto.setFallback(true);
            return;
        }
        String summary = extractSection(llmAnswer, "RESUME");
        List<String> alerts = extractList(llmAnswer, "ALERTES");
        List<String> args = extractList(llmAnswer, "ARGUMENTS_CLIENT");
        List<String> checklist = extractList(llmAnswer, "CHECKLIST_TERRAIN");

        if (summary != null) {
            dto.setNarrativeSummary(summary);
        }
        if (!alerts.isEmpty()) {
            dto.getAlerts().addAll(alerts);
        }
        if (!args.isEmpty()) {
            dto.getClientArguments().addAll(args);
        }
        if (!checklist.isEmpty()) {
            dto.getTerrainChecklist().addAll(checklist);
        }
    }

    /** Default deterministic narrative when the LLM is unavailable. */
    private void applyDeterministicNarrative(InstallerRecommendationDto dto,
                                             SolarInstallation installation,
                                             FinancialMetrics financials) {
        InstallerRecommendationDto.RecommendedKit kit = dto.getRecommendedKit();
        StringBuilder summary = new StringBuilder();
        if (kit != null && kit.getInverter() != null) {
            summary.append("Kit retenu : onduleur ")
                    .append(kit.getInverter().getBrand()).append(' ')
                    .append(kit.getInverter().getModel()).append(" (")
                    .append(String.format("%.1f kW", kit.getInverter().getPowerKw()))
                    .append("), câble DC ")
                    .append(kit.getDcCable() != null ? kit.getDcCable().getSectionMm2() : 0.0)
                    .append(" mm², disjoncteurs Schneider. ");
        }
        summary.append(String.format("Score de compatibilité %d/100 (%s).",
                dto.getCompatibilityScore(), dto.getVerdict()));
        dto.setNarrativeSummary(summary.toString());

        // Default sales arguments from the financial metrics.
        if (financials != null && dto.getClientArguments().isEmpty()) {
            if (financials.getAnnualSavings() != null && financials.getAnnualSavings() > 0) {
                dto.getClientArguments().add(String.format(
                        "Économies estimées : %.0f TND/an, soit ~%.0f TND/mois.",
                        financials.getAnnualSavings(), financials.getAnnualSavings() / 12.0));
            }
            if (financials.getPaybackPeriodYears() != null) {
                dto.getClientArguments().add(String.format(
                        "Retour sur investissement en %.1f ans.",
                        financials.getPaybackPeriodYears()));
            }
            if (financials.getNetSavings25Years() != null) {
                dto.getClientArguments().add(String.format(
                        "Économies cumulées sur 25 ans : %.0f TND.",
                        financials.getNetSavings25Years()));
            }
        }
        if (dto.getTerrainChecklist().isEmpty()) {
            dto.getTerrainChecklist().add("Installer un parafoudre type 2 côté DC.");
            dto.getTerrainChecklist().add("Vérifier l'orientation sud ±15°.");
            dto.getTerrainChecklist().add("Respecter les sections câbles préconisées (NFC 33-209).");
        }
    }

    // ───────────────────────────────────────────────────────────────────
    // Tiny markdown parser for the LLM response
    // ───────────────────────────────────────────────────────────────────

    private static String extractSection(String text, String header) {
        int start = text.indexOf(header + ":");
        if (start < 0) return null;
        int from = start + header.length() + 1;
        int end = text.indexOf('\n', from);
        if (end < 0) end = text.length();
        return text.substring(from, end).trim();
    }

    private static List<String> extractList(String text, String header) {
        List<String> out = new ArrayList<>();
        int start = text.indexOf(header + ":");
        if (start < 0) return out;
        int from = start + header.length() + 1;
        // Stop at the next ALL_CAPS header or end of text.
        int end = text.length();
        for (String stop : List.of("RESUME:", "ALERTES:", "ARGUMENTS_CLIENT:",
                "CHECKLIST_TERRAIN:")) {
            int idx = text.indexOf(stop, from);
            if (idx > from && idx < end) {
                end = idx;
            }
        }
        String body = text.substring(from, end);
        for (String line : body.split("\\r?\\n")) {
            String trimmed = line.trim();
            if (trimmed.startsWith("-")) {
                String item = trimmed.substring(1).trim();
                if (!item.isEmpty()) {
                    out.add(item);
                }
            }
        }
        return out;
    }

    // ───────────────────────────────────────────────────────────────────
    // Misc helpers
    // ───────────────────────────────────────────────────────────────────

    private static String readString(String json, String key) {
        if (json == null) return null;
        int idx = json.indexOf("\"" + key + "\"");
        if (idx < 0) return null;
        int colon = json.indexOf(':', idx);
        int quote = json.indexOf('"', colon + 1);
        if (quote < 0) return null;
        int end = json.indexOf('"', quote + 1);
        return end < 0 ? null : json.substring(quote + 1, end);
    }

    private static String readPhase(Equipment e) {
        return e == null ? null : readString(e.getSpecifications(), "phase");
    }

    private static Integer readInt(String json, String key) {
        if (json == null) return null;
        int idx = json.indexOf("\"" + key + "\"");
        if (idx < 0) return null;
        int colon = json.indexOf(':', idx);
        if (colon < 0) return null;
        int i = colon + 1;
        while (i < json.length() && Character.isWhitespace(json.charAt(i))) i++;
        int start = i;
        while (i < json.length() && "-0123456789".indexOf(json.charAt(i)) >= 0) i++;
        if (start == i) return null;
        try {
            return Integer.parseInt(json.substring(start, i));
        } catch (NumberFormatException ex) {
            return null;
        }
    }

    private static double nz(Double v) {
        return v != null ? v : 0.0;
    }

    /** Composite output kept lightweight to avoid leaking the DTO type. */
    public record Result(InstallerRecommendationDto recommendation,
                         String narrativeSummary) {

        @SuppressWarnings("unused")
        public BigDecimal totalKitPrice() {
            return recommendation == null || recommendation.getRecommendedKit() == null
                    ? BigDecimal.ZERO
                    : recommendation.getRecommendedKit().getTotalKitPrice();
        }
    }
}
