spring.application.name=project-service
server.port=8082

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/solarease_projects
spring.datasource.username=louay
spring.datasource.password=SolarEase2026!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
