apiVersion: v1
kind: ConfigMap
metadata:
  name: solarease-config
  namespace: solarease
  labels:
    app.kubernetes.io/part-of: solarease
data:
  POSTGRES_USER: "postgres"
  IDENTITY_SERVICE_URL: "http://identity-service:8081"
  PROJECT_SERVICE_URL: "http://project-service:8082"
  DIMENSIONING_SERVICE_URL: "http://dimensioning-service:8083"
  OLLAMA_BASE_URL: "http://ollama:11434"
  OLLAMA_MODEL: "tinyllama:latest"
  APP_FRONTEND_URL: "http://frontend"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SOLAREASE_DEMO_SEED: "false"
  APP_JWT_EXPIRATION: "86400000"
  APP_JWT_REFRESH_EXPIRATION: "604800000"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
