apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solarease

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.template.yaml
  - postgres-identity.yaml
  - postgres-project.yaml
  - postgres-dimensioning.yaml
  - ollama.yaml
  - identity-service.yaml
  - project-service.yaml
  - dimensioning-service.yaml
  - gateway-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: solarease
  app.kubernetes.io/managed-by: kustomize
